<?php

namespace DoctrineProxies\__CG__\App\Entities;


/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Email extends \App\Entities\Email implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Proxy\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Proxy\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array<string, null> properties to be lazy loaded, indexed by property name
     */
    public static $lazyPropertiesNames = array (
);

    /**
     * @var array<string, mixed> default values of properties to be lazy loaded, with keys being the property names
     *
     * @see \Doctrine\Common\Proxy\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array (
);



    public function __construct(?\Closure $initializer = null, ?\Closure $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return ['__isInitialized__', '' . "\0" . 'App\\Entities\\Email' . "\0" . 'id', '' . "\0" . 'App\\Entities\\Email' . "\0" . 'main', '' . "\0" . 'App\\Entities\\Email' . "\0" . 'recovery', '' . "\0" . 'App\\Entities\\Email' . "\0" . 'verified', '' . "\0" . 'App\\Entities\\Email' . "\0" . 'verifiedAt', '' . "\0" . 'App\\Entities\\Email' . "\0" . 'hashVerified', '' . "\0" . 'App\\Entities\\Email' . "\0" . 'user'];
        }

        return ['__isInitialized__', '' . "\0" . 'App\\Entities\\Email' . "\0" . 'id', '' . "\0" . 'App\\Entities\\Email' . "\0" . 'main', '' . "\0" . 'App\\Entities\\Email' . "\0" . 'recovery', '' . "\0" . 'App\\Entities\\Email' . "\0" . 'verified', '' . "\0" . 'App\\Entities\\Email' . "\0" . 'verifiedAt', '' . "\0" . 'App\\Entities\\Email' . "\0" . 'hashVerified', '' . "\0" . 'App\\Entities\\Email' . "\0" . 'user'];
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Email $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy::$lazyPropertiesDefaults as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', []);
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load(): void
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', []);
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized(): bool
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized): void
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null): void
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer(): ?\Closure
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null): void
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner(): ?\Closure
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @deprecated no longer in use - generated code now relies on internal components rather than generated public API
     * @static
     */
    public function __getLazyProperties(): array
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function setId(int $id): \App\Entities\Email
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setId', [$id]);

        return parent::setId($id);
    }

    /**
     * {@inheritDoc}
     */
    public function getId(): int
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', []);

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function setMain(string $main): \App\Entities\Email
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setMain', [$main]);

        return parent::setMain($main);
    }

    /**
     * {@inheritDoc}
     */
    public function getMain(): string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getMain', []);

        return parent::getMain();
    }

    /**
     * {@inheritDoc}
     */
    public function setRecovery(string $recovery): \App\Entities\Email
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setRecovery', [$recovery]);

        return parent::setRecovery($recovery);
    }

    /**
     * {@inheritDoc}
     */
    public function getRecovery(): string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getRecovery', []);

        return parent::getRecovery();
    }

    /**
     * {@inheritDoc}
     */
    public function setVerified(bool $verified): \App\Entities\Email
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setVerified', [$verified]);

        return parent::setVerified($verified);
    }

    /**
     * {@inheritDoc}
     */
    public function getVerified(): bool
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getVerified', []);

        return parent::getVerified();
    }

    /**
     * {@inheritDoc}
     */
    public function setVerifiedAt(?\DateTime $verifiedAt): \App\Entities\Email
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setVerifiedAt', [$verifiedAt]);

        return parent::setVerifiedAt($verifiedAt);
    }

    /**
     * {@inheritDoc}
     */
    public function getVerifiedAt(): ?\DateTime
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getVerifiedAt', []);

        return parent::getVerifiedAt();
    }

    /**
     * {@inheritDoc}
     */
    public function setHashVerified(?string $hashVerified): \App\Entities\Email
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setHashVerified', [$hashVerified]);

        return parent::setHashVerified($hashVerified);
    }

    /**
     * {@inheritDoc}
     */
    public function getHashVerified(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getHashVerified', []);

        return parent::getHashVerified();
    }

    /**
     * {@inheritDoc}
     */
    public function setUser(\App\Entities\User $user): \App\Entities\Email
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setUser', [$user]);

        return parent::setUser($user);
    }

    /**
     * {@inheritDoc}
     */
    public function getUser(): \App\Entities\User
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getUser', []);

        return parent::getUser();
    }

}
